summary/README.md, summary/requirements.txt, summary/summary.py
We should add pretty-printing to lightning-cli (with an option to disable), and remove it from lightningd.  That would be faster, too, and avoid messy plugin output.
=> Summary: simple plugin which got out of hand.

summary/summary.py
Improves some minor output issues:
- Adds short channel id, so it can be copy and pasted for rebalancing
- renames `channels_key` to `channels_flags`
- replace `=` with `:` in `channels_flags`, looks better in -H or JSON output.
- changes flags round rackets (PO) to squace brackets [PO]
- Always outputs flags even if not set `[__]` so things are always aligned
- Removes the colon ':' and always prints a space
this also helps when copy and pasting in a terminal
TLDR: Output will now look like this (with correct special char alignment which GitHub mess up):
```
channels_flags=P:private O:offline
channels=
├──────────────────┼───┤                    1511185x45x0   [__] testnet1-lnd.zaphq.io
├──────────────────────╢                        1511189x47x0   [P_] CoinGate
├─────────────────────┼┤ …
```
=> feat: add scid to summary output

summary/summary.py
Not sure if this is a universal issue, price thread crashes while setting fiat_per_btc  as r.content is raw data. Running: packaging==19.0, requests==2.9.1 and pylightning==0.0.7.
=> raw response fix

rebalance/README.md, rebalance/rebalance.py
I improved the UX of the rebalance plugin a bit:
- rebalance amount parameter will now optionally calculate for a 50% balancing if possible
- workaround a bug where outdated pylightning version will raise a exception (https://github.com/ElementsProject/lightning/pull/2601)
- some minor cleanups
Possible further TODOs:
- account for `their_reserve_msat` `our_reserve_msat` `spendable_msat` in `calc_optimal_amount`
- try sending several smaller payments if rebalance fails along the route
=> Improve rebalance

sendinvoiceless/README.md, sendinvoiceless/sendinvoiceless.py
This will add the command `receivedinvoiceless` which will
show the recent payments/donations being made to your node.
The plugin can be called like below. It will filter results by `min_amount` (default: `10sat`).
```
lightning-cli receivedinvoiceless [min_amount]
```
```
lightning-cli receivedinvoiceless 
[
{
"amount_msat" : "999600msat",
"amount_btc" : "0.00001000btc",
"resolved_time" : 1556558261.481,
"timestamp" : "2019-04-29 17:17:41 (UTC)"
}
]
```
The plugin currently does not use a database, so it can only assume fees did not change in the past. else will produce slightly false results.
=> sendinvoiceless list received payments

README.md, autoreload/README.md, autoreload/autoreload.py, autoreload/requirements.txt
A simple plugin that can be used to speed plugin development by having the
plugin under development be reloaded whenever its executable changes, or when
triggered automatically.
=> autoreload: Add an autoreload plugin to restart plugins on change

prometheus/prometheus.py
With c-lightning v0.7.0, there seems to be no `short_channel_id`
key present in the input sent to the `prometheus.py` script when
it is is called via the `plugin` config value for c-lightning
when a channel is opened.
Without this change, the script throws `500 Internal Server` error
when doing `$ lightning-cli fundchannel <id> <sats>`.
A sample JSON messages passed to the plugin is:
```
{
'state': 'CHANNELD_AWAITING_LOCKIN',
'scratch_txid': '120ad265b66aa0c4bbb5ff50a23ca85463337fb8b58b395f3811918610686a734',
'owner': 'lightning_channeld',
'channel_id': 'eda784df73aa105d728a0d9fee6ff450eeeac78aa57d3218f7b0dd89b2bd20f1',
'funding_txid': 'f120bdb2eec4b0f718327dc58cc7eaee5dd46fa19f0d8a725d10ff73df84a7ed',
'private': False,
'funding_allocation_msat': { …
```
=> prometheus: Fix channel_id name and prevent crashing

summary/summary.py
When the summary plugin starts, it runs a thread to discover the current
`fiat_per_btc` price. When this was not finished yet, the `if` statement
in line 112 fails, because this in not JavaScript and the property has
to be checked with `hasattr(obj, key)` method in order to not throw an
exception.
=> fix: a race condition in the summary plugin

README.md, rebalance/README.md, sendinvoiceless/README.md
This PR adds a unified and more complete plugin installation instruction guide in the main `README.md` so things must not be duplicated in the plugins subdirectories docs anymore. The plugins docs can simply reference to the main guide.
=> Doc readme install

prometheus/prometheus.py
This metric is useful on initial sync, when bitcoind is already synced, but lightningd is still working through the blocks. Comparing the two measures allows to calculate the indexing progress.
=> add lightningd blockheight metric

rebalance/rebalance.py
The channel selection query didnt filter for channels not
having a short_channel_id yet (unconfirmed ones).
This lead to a KeyError whenever an unconfirmed channel existed.
=> fix: rebalance channel selection

README.md
This documents the recently merged https://github.com/ElementsProject/lightning/pull/2647
that points the users to organize their plugins not by a growing cascade of `--plugin` arguments, but to put them in `~/.lightning/plugins/...`
=> doc: auto plugin directories. main repo issue 2647

rebalance/rebalance.py
This should solve #29 where the auto amount calculation created decimal `123.0msat` amounts.
I think this issue happens on older version of pylightning only.
=> rebalance: fix issue 29

rebalance/rebalance.py
This was really stupid, before merging the last one, I added hard parameter casting at the top of the function without testing the amount `msatoshi` parameter for default (None) that was then used to call `Millisatoshi(None)`.
=> rebalance: fix amount None

rebalance/rebalance.py
This will set the correct `direction` on manual route hops first and last (in/out).
Before this was not set, resulting in WIRE_FEE_INSUFFICIENT errors,
if fee was calculated (correctly) but inconsistently with `direction`, defaulting perhaps to `0`.
The error occurred on `sendpay` doing checks for the route I guess. I noticed this when having WIRE_FEE_INSUFFICIENT errors on last hop, where my peer had a higher fee setting than me and direction should have been 1.
=> rebalance: fix route direction

README.md
This is an http/https passthrough to/from the unix socket allowing remote rpc calls
=> add remoteRPC plugin

autopilot/autopilot.py, autopilot/requirements.txt
- Resolves issue #41 by adding fixing the failing call attempting to iterate over `random.shuffle()`. 
- some additional error handling so that we continue onto other peers in the event one fails to connect
- missed imports encountered on the path when no peers present
- missed dependency in requirements file
=> autopilot functional peer searching when no peers connected

README.md
A plugin which can search for plugins from known plugin locations (such as this repo) and install them.
=> Add a link to the reckless plugin manager in the README

autopilot/autopilot.py, autoreload/autoreload.py
Cf [RPC plugins management](https://github.com/ElementsProject/lightning/pull/2771).
I tested all plugins from the repo and (aside from a little issue with socket absolute path in Pylightning), `autopilot` and `autoreload` were the only two requiring to be loaded at `lightningd` startup. Hence, I made in anticipation of the next release, the change to set the `dynamic` member to `False`.
I prefered a `try`...`except` over an additional dependency to check version numbers.
=> Specify startup-only plugins to be non-dynamic

helpme/helpme.py
A tiny fix to wrap `response` in `{'text': response, 'format-hint': 'simple'}`, so it looks better in lightning-cli.
=> helpme: Wrap in `simple` format-hint, so lightning-cli prints it as -H

rebalance/rebalance.py
[BOLT \#7](https://github.com/lightningnetwork/lightning-rfc/blob/v1.0/07-routing-gossip.md#htlc-fees) requires that nodes “SHOULD accept HTLCs that pay a fee equal to or greater than:  
`fee_base_msat + ( amount_to_forward * fee_proportional_millionths / 1000000 )`”.
The code in `rebalance.py:setup_routing_fees` was not strictly meeting the above requirement, as it was using truncating integer division to calculate the proportional part of the fee, which typically results in a fee that is strictly less than the theoretical, infinite-precision, required fee. Some node implementations may allow rounding down here, but some do not, resulting in sporadic `WIRE_FEE_INSUFFICIENT` errors.
This commit changes the fee calculation in `setup_routing_fees` so that it always rounds up to the next …
=> rebalance: round HTLC fees up

helpme/helpme.py
Small fix:
Using `sum()` on Millisatoshi does not work and throws a TypeError.
We have to do the ugly `Millisatoshi(1000 * sum([value]))` way if we want to use `sum()`.
Note: also the plugin config detection does not seem to work as it should when using the default `~/.lightning/plugins` directory. The output from the **plugin** does not make sense in this context: 
```
...
STAGE 6 (adding bling): You have not added plugins.  Try 'helpme plugins'
```
=> fix: making sum() of funds iteration did not work on non-numeric

sendinvoiceless/sendinvoiceless.py
This will apply the same fee rounding error correction as done to rebalance to the sendinvoiceless plugin:
```
477bdd8 rebalance: round HTLC fees up
```
=> sendinvoiceless: round HTLC fees up

sendinvoiceless/sendinvoiceless.py
Applies the same  py3.5 compat fix to sendinvoiceless:
94c641e rebalance: restore Python3.5 compat
=> sendinvoiceless: restore Python3.5 compat

drain/README.md, drain/drain.py, drain/requirements.txt
This plugin offers three new commands: `drain`, `fill` and `setbalance`.
It works similar to the `rebalance` plugin but with some key differences:
- Does not need a second `scid` parameter but figures out the other one by routing.
- Can have chunked payments that increases routing probability but can result in partial completion. If `cunks` is not set, number of required chunks is autodetected.
- Does not consume or calculate msat amounts, but uses percentages. Default `100` for `drain` and `fill` and `50` for `setbalance`.
Note: If draining 100%, the plugin guesses the correct HTLC fee by try and error. For new servers that report HTLC fee via exception (https://github.com/ElementsProject/lightning/pull/2691) it takes the exact amount.
Issues:
- Can run into "route not found" errors …
=> drain and fill channel plugin

autopilot/requirements.txt
Graph.node has been renamed to Graph.nodes in version 2.4 at provokes a failure when running autopilot
=> Fix networkx version

README.md, zmq/README.md, zmq/cl-zmq.py, zmq/example-subscriber.py
A plugin that subscribes to notification and passes them through to be published to ZeroMQ endpoints. It utilizes Twisted and txZMQ to facilitate the publication. An additional script is provided to serve as an example for how to subscribe to the events.
The presentation was chosen to follow how `bitcoind` sets up its ZMQ publishing functionality.
NOTE: The plugin source file is given the name `cl-zmq.py` as opposed to `zmq.py` because the package dependencies import the official ZeroMQ python packages via `from zmq import ...` which is a namespace conflict with a source file named `zmq.py`.
=> ZeroMQ publisher plugin

jitrebalance/jitrebalance.py, jitrebalance/requirements.txt, jitrebalance/test_jitrebalance.py
A simple implementation of a jit-rebalance plugin based in the idea of
@renepickhardt. Upon receiving an HTLC that we are supposed to forward check
whether the channel has sufficient capacity to forward. If that's not the case
we need to rebalance. For this we compute a circular route through some other
nodes, returning funds on the edge we are supposed to use when
forwarding. This means we rebalance the channel just enough to make forwarding
possible.
This only implements the simple version, without FOAF advertisements of free
rebalancings, but it already works rather nicely.
Suggested-by: Rene Pickhardt <@renepickhardt>
Signed-off-by: Christian Decker <@cdecker>
=> jitrebalance: First version of the JITrebalance plugin

README.md
I've written plugins for c-lightning implementing `lncli feereport` and `lncli walletbalance`. Decided to put them together in a single repo as a submodules. Idea is that other people doing similar stuff (implementing `lncli` stuff for c-lightning) could add their plugins there too in future.
=> Add link to plugin collection emulating some of the LND (lncli) commands on c-lightning

.gitignore, .travis.yml, .travis/bin/python3, .travis/build.sh, README.md
This PR adds the ability to run `coverage` inside a plugin, to check how well
the tests exercise the available functionality. The way we achieve this is by
providing a small wrapper around `python3` in `.travis/bin/` which is added to
the `$PATH` before the actual `python3` binary. The wrapper calls `coverage
run` instead of `python3` directly, and makes sure that the coverage results
are stashed in separate files in `/tmp/.coverage.*`. The results are then
combined into a single coverage file and `coveralls` is called to deliver the
coverage results to coveralls.io where we can track progress.
In order to use the wrapper we need to have the folloing shebang:
```bash
#!/usr/bin/env python3
```
This will make sure that the `python3` executable is picked from the `$PATH`
variable and thus …
=> Add coverage for python plugins

sauron/art.py, sauron/requirements.txt, sauron/sauron.py
This a minimal version of a Bitcoin backend plugin for C-lightning which hits Esplora.
The minimal version is mostly for demonstration purpose for the C-lightning PR.
Quirks:
- Esplora doesn't serve raw blocks (yet?) https://github.com/Blockstream/esplora/issues/171
- If we prefer to keep this name for watchtowers, I can understand ^^
=> WIP: Sauron, the Bitcoin network watcher

README.md, sauron/README.md, sauron/sauron.py
After https://github.com/ElementsProject/lightning/pull/3570 was merged.
I used a higher feerate for HTLC resolution and penalty transaction, as per https://github.com/ElementsProject/lightning/pull/3592. What do you think ?
=> Adapt Sauron to the new lightningd

backup/backup.py, backup/requirements.txt
Before this change, backup backend was initialized twice - in on_init()
and get_backend() functions. This change leaves only one call in
get_backend() and adds a kwarg determining whether init failure should
be fatal.
Signed-off-by: Michal Rostecki <mrostecki@mailfence.com>
=> backup: Remove duplicate call of initialize()

prometheus/prometheus.py
Prometheus 2.7.1+ds apparently doesn't accept hyphens in label names. Replacing them with underscores fixes the error I got otherwise:
```
error while linting: text format parsing error in line 3: expected '=' after label name, found '-'
```
=> Prometheus: avoid hyphens in label names

helpme/helpme.py
Within the if-block the list `parts` obviously only consists of one element, so the access `[1]` fails. 
Probably fixes #59
=> helpme: fix out of range access in configfile parser

.travis/build.sh, jitrebalance/jitrebalance.py, jitrebalance/test_jitrebalance.py
Fixes two issues in the jitrebalance plugin:
- Unchecked access to a `dict` field: we were accessing the `short_channel_id` key in the channel `dict`, which is not safe for unconfirmed channels. This would crash the plugin, taking the rest of the node with it.
- The `Millisatoshi` class includes checks for negative numbers, which were a bit overzealous. We not check before doing the computation, and return early if the channel capacity is sufficient.
Fixes #88
=> Fix an issue with unchecked dict field access in jitrebalance

jitrebalance/jitrebalance.py
While testing https://github.com/lightningd/plugins/pull/114 for real, I encountered the following error at the first rebalancing attempt :
```
2020-05-25T09:18:57.477Z INFO plugin-jitrebalance.py: Excluding 620929x1921x1 due to a failed attempt
2020-05-25T09:18:57.531Z UNUSUAL plugin-jitrebalance.py: Exception in thread Thread-1:
2020-05-25T09:18:57.531Z UNUSUAL plugin-jitrebalance.py: Traceback (most recent call last):
2020-05-25T09:18:57.531Z UNUSUAL plugin-jitrebalance.py:   File \"/usr/lib/python3.5/threading.py\", line 914, in _bootstrap_inner
2020-05-25T09:18:57.531Z UNUSUAL plugin-jitrebalance.py:     self.run()
2020-05-25T09:18:57.532Z UNUSUAL plugin-jitrebalance.py:   File \"/usr/lib/python3.5/threading.py\", line 862, in run
2020-05-25T09:18:57.532Z UNUSUAL …
```
=> Jitrebalance fixes

prometheus/prometheus.py
For example : `lightning_channel_htlcs{id="02065e25c272203440b66ea0ba66601d1248564554d0a68472b82511af54288120",scid="f93c2d2af0f1abf88b77bd2f014e06fbf064c18199ddb20e197195b2dc492b6c"} 1.0`
=> prometheus: give short channel id for scid fiels, not long one

autopilot/lib_autopilot.py
Without this fix I get:  AttributeError: 'Graph' object has no attribute 'node' (freshly installed networkx)
https://networkx.github.io/documentation/stable/release/release_2.4.html#deprecations claims it's not G.node anymore, but G.nodes is to be used now. Worked for me.
=> G.node -> G.nodes

autopilot/autopilot.py, autopilot/lib_autopilot.py
This fixes two problems my autopilot kept running into:
1) trying to fund too large channels, which failed for this reason
2) having only one UTXO, which backfired when it tried to fund more than one channel via autopilot at once, as it would only accept UTXOs with several confirmations to fund a channel. So only the first channel got funded and then I got errors for all others as the new UTXOs were still unconfirmed.
=> Limit channel size, don't require confirmations for channel funding

README.md, summary/summary.py, summary/summary_avail.py, summary/test_summary.py
Adds:
- peer availability tracing, to show the node operator which peers are reliable.
- 72hr exponential smoothing window
Fixes:
- fix broken fiat price API by switching to public (and reliable) bitstamp ticker API.
- fix PriceThread actually perform a loop instead of fetching price only one time
=> feat: summary peer availability tracing

summary/summary.py
This adds basic persistence support for availability data.
The file `summary.dat` will be located at the cln working directory, so for testnet this is `~/.lightning/testnet/summary.dat` .
Currently there's no versioning and content checks, this can be added later, if required.
=> summary: persist peerstate via shelve

summary/summary.py, summary/summary_avail.py, summary/test_summary.py
Recovered persistent availability data was average out too fast, as a restarted node came up with a peerstate thread execution count of 0. Because the count being 0 the shortened leading exponential smoothing window was too small, leading to the situation that the recovered data was average out very quickly.
This commit takes the avail_count variable into the persistent state and adds a test.
=> summary: fix persistent peerstate zero leading window

sauron/sauron.py
Sauron would fail with a 500 error or 429 error from time to time, so we now retry with a linear backoff.
Ping @darosior :-)
=> sauron: Add retry HTTP adapter to retry requests up to 10 times

prometheus/README.md, prometheus/prometheus.py
We registered port 9750 the [port allocation] list for the prometheus project,
so we should use that port :-)
The addition to the list of known exporters is still pending https://github.com/prometheus/docs/pull/1737
Suggested-by: Martin Milata <@mmilata>
Fixes #122
[port allocation]: https://github.com/prometheus/prometheus/wiki/Default-port-allocations
=> prometheus: Change default port to 9750 as per port-allocation

drain/test_drain.py
I simply increased the allowed margin by a percent.
I could try to find out what experimental feature caused this,
but I don't think that's helpful, as I will need to work on the
precision of percentage wise drains anyway.
=> drain: fix test for clnd with exp features

feeadjuster/feeadjuster.py, feeadjuster/requirements.txt, feeadjuster/test_feeadjuster.py
This is really just a sketch, but i wanted to share the algorithm with you in case you have inputs.
This is structured such as it should be easy to set the `get_ratio` function depending on configuration flags. For example we can imagine a `--feeadjust-algo` option which would default to `basic` and just use the current one, and a `greedy` value would biase the ratio depending on:
- the funds on our side (how much we are exposed)
- if we are the channel funder (even worse, in practice this is my main source of losses)
- maybe the number of HTLCs in flight (this would actually take YA rpc call)
While this is an experiment i expect to run this on a node forwarding a substantial number of payments per day, so care has been taken to minimize the impact (mainly reduce the number of RPC calls). …
=> feeadjuster: a plugin to adjust fees depending on channel balancing

README.md, feeadjuster/feeadjuster.py, feeadjuster/test_feeadjuster.py
These are my additions on the feeadjuster:
- fix some typos
- remove useless loop (again :)
- adds `feeadjuster-imbalance`% config option that keeps the plugin from acting if imbalance is too low
- add it to the repo's REAMDME.md link
**Note:** The default value for `feeadjuster-imbalance` is 50% (always on), as I didn't want to change current function and just improve on it. However, again, for privacy reasons I propose to use a value of i.e. 30% of letting the `feeadjuster` to set fees only when imbalance exceeds 30/70%. In any case, I can now use this value for myself now ;)
I think about adding an additional loop that sets default base/ppm fees on a per channel basis by doing some peer analysis as @zmnscpxj suggested. Maybe this can be an optional dedicated plugin that needs to run …
=> chore: feeadjuster additions

summary/requirements.txt, summary/summary.py
All plugins should take care to do this if config
specifies always-use-proxy!
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
=> summary: use proxy if configuration says to.

summary/summary.py, summary/test_summary.py
1. Bitstamp API error occasionally returning 404
2. proxy config check can also be false!
3. test flake that was introduced likely by main repo changes in `pyln-testing`
=> summary: fix minor bugs

backup/backup.py, backup/test_backup.py
We address #155 by deprecating the `--backup-destination` CLI option, replacing it outright with the discovery based on the `backup.lock` file, which is generated by `backup-cli init [lightning-dir] [backend-uri]`. This means that we can immediately start appending changes to the backup without having to wait for the `init` message from `lightningd` (at which point we'd already have some writes buffered).
The `--backup-destination` flag is still present so we don't break any config files, but we warn about it being present, and ask the operator to fix their config.
Fixes #155
=> backup: Do not buffer early writes, instead rely on backup.lock to find and write to the backend

feeadjuster/feeadjuster.py, feeadjuster/test_feeadjuster.py
A new method has been added to adjust fees for all of your channels. Automatically called in plugin init, or can be called manually after a successful payment.
=> feeadjuster: a new method added to adjust all existing channels

.github/workflows/main.yml, README.md
The travis badge is no longer useful.
=> Update the readme to include a Github Actions badge

noise/README.org, noise/noise.py
As pointed out by @Fonta1n3 in #136, the docs were incorrect when it comes to
waiting for the next message. The docs have been updated accordingly.
Fixes #136
=> noise: Fixup documentation about waiting for next message

prometheus/prometheus.py
This contribution provides prometheus with an extra label option for the channels. You can now choose for peer id, channel id, and node alias. (this helped me to understand the graph's better without having to look up the id every time.) 
i notice now that the default listening port has changed, please edit that line away (i think that is just my config). 
Since it's my first commit ever, please provide feedback.
=> prometheus plugin: Added node alias to channel label for human readable legend

rebalance/README.md, rebalance/rebalance.py
- rebalances liquidity between channels through circular payments
- automatically selects appropriate channels and executes rebalance
- uses economic fee by default: the rebalance transaction fees are less than the node's default fee, so it is cheaper to fix the liquidity than it can be ruined by transaction forwards
- runs async in the background, sometimes for a very long time (maybe hours)
- tries to rebalance small channels to a 50/50 liquidity ratio and stores remaining liquidity in big channels
- does nothing if there is no cheap enough circular route for rebalance
=> automatic rebalance

backup/backup.py, backup/test_backup.py
Fundamentally backups using the `FileBackend` are just a snapshot of the
`sqlite3` database followed by incremental changes that are applied on
top of that snapshot. This means that backups will grow indefinitely
over time, and may cause some issues:
- Long restore time: the more changes are appended to a backup the
longer it takes to apply them on restore.
- Large files: we had reports of users running on fat32, which fails
spectacularly when the filesize exceeds 2GB
This PR implements compactions for the `FileBackend`, by performing
the following steps:
- `lightning-cli backup-compact` initiates the compaction
- The existing backup is taken, and restored up to the second to last
change to a new database:
- Extract snapshot
- Apply incremental changes
- A new snapshot is taken of the …
=> backup: Add the ability to compact the backups

feeadjuster/feeadjuster.py
cannot call a method from python framework with underscore in its name
https://github.com/ElementsProject/lightning/blob/6f924e63c2e7280b19419d589cca207cfbe6216d/contrib/pyln-client/pyln/client/lightning.py#L316
=> feeadjuster: no underscore in method name

feeadjuster/feeadjuster.py, rebalance/rebalance.py
After small chat with cdecker, using dash/minus in RPC name is good and will be translated to underscore in pyln on the fly.
=> chore: renames RPC feeadjusttoggle to feeadjust-toggle

backup/backup.py
'fixes' https://github.com/lightningd/plugins/issues/209
I commented out that check and placed a NOTE that future developers
to see upfront putting in RPC stuff in init is potentially bad.
=> backup: fix deadlock by removing the sqlite3 check

historian/gossipd.py
Fixes an exception thrown for not having a parser for message type 4103. These messages are now just ignored (maybe should be handled somehow?)
=> Fix missing parser error

historian/historian.py
`gossipd` was referred to as `parser` resulting in errors.
=> Fix reference to gossipd in historian.py

historian/historian.py
Fixes a bug where `historian-stats` would give IndexError when no announcements or updates where recorded yet.
=> Avoid out of IndexError from `historian-stats`

rebalance/rebalance.py, rebalance/test_rebalance.py
Currently, when we have 100% of the liquidity on our side run (expected) into the `rebalanceall` finishing without doing anything.
This is very rarely, but it can be confusing, so we add a pre-check that returns an error on `rebalanceall` in that scenario.
See:  https://github.com/lightningd/plugins/issues/205#issuecomment-772676555
=> rebalance: adds a check for no incoming liquidity

historian/historian.py
Fixes a bug where gossip messages that are ignored by the historian plugin will trigger an exception being printed.
=> Fix handling of ignored messages in historian.py

backup/remote.md, backup/socketbackend.py, backup/test_backup.py
Support the bracketed `socket:[::]:1234` syntax for IPv6 addresses.
Also, factor out the socket URI parsing to a function and add tests for it. 
As a forward compatibility measure, reject query strings (`?a=b`) because I intend to use these for parameters such as SOCKS5 proxy (for Tor) in a future patch.
=> backup: Add support for IPv6 addresses in socket backend

paytest/README.org, paytest/paytest.py, paytest/requirements.txt, paytest/test_paytest.py
With the introduction of the `pay` plugin, its modifiers, and
especially the MPP support, we have introduced quite a few new
parameters that need optimization. Since these optimizations depend on
the topology of the network and the behavior of the nodes in the
network, we should be testing on the real network. However, to do so
safely, and without putting the tester's funds at risk requires us to
get a bit tricky.
`paytest` is a plugin that is to be deployed both on the sender and
the recipient of the route to be tested. It'll pretend to accumulate
parts of a payment, and time them out correctly on the recipient side,
while it ensures that the sender's funds are safe, by paying an
invoice that the recipient cannot really settle.
=> paytest: A plugin to test multi-part payments and optimize the `pay` plugin

currencyrate/currencyrate.py
root@ubuntu-s-4vcpu-8gb-nyc3-01:~# l2-cli currencyrates USD
{
"code": -32600,
"message": "Error while processing currencyrates: argument of type 'int' is not iterable",
"traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/pyln/client/plugin.py\", line 621, in _dispatch_request\n    result = self._exec_func(method.func, request)\n  File \"/usr/local/lib/python3.8/dist-packages/pyln/client/plugin.py\", line 603, in _exec_func\n    return func(*ba.args, **ba.kwargs)\n  File \"/root/plugins/currencyrate/currencyrate.py\", line 121, in currencyrates\n    return get_rates(plugin, currency.upper())\n  File \"/usr/local/lib/python3.8/dist-packages/cachetools/decorators.py\", line 22, in wrapper\n    v = func(*args, **kwargs)\n  File …
=> currencyrate: fix what happens when we get an error.

backup/remote.md, backup/socketbackend.py, backup/test_backup.py
Add support for connecting to the backup server through Tor, via its SOCKS5 proxy. This adds a way to configure proxies in the socket backend URL scheme. Only one type of proxy is supported for now (but the scheme allows for e.g. I2P SAM in the future).
See [Usage with Tor](https://github.com/lightningd/plugins/blob/ebf5ed6fdd1ffac804f48e3ca6926602d7a2ed0b/backup/remote.md#usage-with-tor) in remote.md for documentation.
Next step after this is configurable auto-reconnect behavior. Tor HS connections are less reliable than say, SSH tunnels over the clearnet, it would be useful if it retries before giving up and shutting down `lightningd`.
=> backup: Add support for Tor in socket backend

backup/backup-cli, backup/server.py
Add two optional arguments to `backup-cli server`:
- `--log-mode`: either `plain` (simply print the log message) or `systemd` (prefix log message with systemd log level, useful for running as a  a service)
- `--log-level`: minimum level for messages to be logged, from `DEBUG` to `CRITICAL`
Also, move some noisy messages to the debug level.
Example systemd service file (might make sense to add this to the documentation):
```
[Unit]
Description=C-lightning backup server
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
User=<user>
ExecStart=<path>/plugins/backup/backup-cli server --log-level debug --log-mode systemd file://<backup> 127.0.0.1:8700
[Install]
WantedBy=multi-user.target
```
=> backup: Improve logging configurability for socket server

probe/probe.py, probe/test_probe.py
We used to only probe for a 10sat amount, which allows us to test
basic reachability, but it doesn't say much about whether we can
actually pay for something reasonable, so this fixes that.
This may require the following SQL statement to be applied to the
database if you are upgrading from a prior version:
```sql
ALTER TABLE probes ADD amount INTEGER;
```
This is not required if you start with a new database.
=> probe: Allow the caller to specify the amount to probe

paytest/paytest.py, paytest/test_paytest.py
We crash the plugin accidentally if we're not handling a paytest but
rather a payment destined for us, due to us falsely assuming the
short-channel-id to be set in the onion
Reported-by: Michael Schmoock <@m-schmoock>
=> paytest: Fix crash reported by m-schmoock on direct payment

rebalance/rebalance.py, rebalance/test_rebalance.py
- this will fix and cleanup some things
- adds a feature where the plugin tries routes first that are more likely to be successful while brute forcing all possible routes later on. Meaning it will try shorter routes first, then a longer routes while simultaneously setting a higher requested capacity to `getroute` method and finally just trying all routes we can get.
- exclude nodes for future getroute requests that produce 4 or more `erring_node` errors (regardless the cause).
=> Rebalance improvements

rebalance/test_rebalance.py
We changed the return message on `rebalancestop`
in the latest commit which the testcase did not expect.
=> rebalance: fix testcase

.ci/test.py, donations/requirements.txt, donations/test_donations.py, noise/test_chat.py, paytest/test_paytest.py, request-invoice/requirements.txt
The root cause was pyln-testing not matching the c-lightning version, and having the fee estimation buckets not matching.
I also went and added some drive-by fixes.
=> Update pyln-testing on CI which broke all tests

feeadjuster/feeadjuster.py
This will cleanup some code and adds a configurable per channel fee strategy instead of always using global config or defaults. 
The new default strategy selects the median fees from the other peers of a peer.
The rational behind is that our node somehow competes towards that target.
The idea was raised by @ZmnSCPxj a while ago on IRC.
Using these median fees as base values for further calculation also feedbacks and reflects the current network state at that local area when/if the the local peers also use some dynamic methods.
=> feeadjuster: fee strategy per channel

.gitmodules, README.md
Finally, I finished testing my RPC wrapper and I would like to push it in this list.
In addition, the bitcoin backend plugin is inspired by #112 #214
A small demo [Demo](https://bruce.bublina.eu.org/) on mainet in pruning mode
Fixes #112 
Fixes #214
=> Adding Java API to the list, and another bitcoin backend

monitor/monitor.py
Sometimes a channels funding allocation was not yet readable
via listpeers which is why this plugin test was flaky.
Also makes use of funding_msat instead of deprecated fields.
=> monitor: fix flakyness

feeadjuster/feeadjuster.py
This will add a runtime check to see if the daemon already supports using `lightning-cli listchannels destination=...` feature https://github.com/ElementsProject/lightning/pull/4614 .
If successful this will be less resource intense.
=> feeadjuster: use listchannels by destination

rebalance/rebalance.py, rebalance/test_rebalance.py
Will make `rebalancestop` also return the last `rebalanceall_msg` event if there was nothing to stop.
This is helpful as `rebalanceall` jobs tend to run very long in the background. This way
the user can still get the result of that job.
=> rebalance: rebalancestop also return last runs message

rebalance/README.md
The parameters were in incorrect order, causing an error when user doesn't use with `-k`
=> rebalance: fix example usage in readme

drain/README.md
percentage instead of 'perecentage'
=> drain: README.md correction

drain/drain.py, feeadjuster/test_feeadjuster.py, jitrebalance/test_jitrebalance.py, rebalance/rebalance.py
We now insist on payment_secret, so rebalance fails!
=> rebalance, feeadjuster, drain, jitrebalance: fix for next release.

datastore/README.md, datastore/datastore-plugin.py, datastore/datastore.py, datastore/requirements.txt
See https://github.com/ElementsProject/lightning/pull/4674
(I manually tested that it passes all the tests there, too!)
When they finally upgrade the node, this automatically puts any
datastore data into the inbuilt datastore and shuts down.
=> datastore: plugin to replicate datastore commands before next release.

backup/backend.py, backup/filebackend.py
Since I run the [clboss](https://github.com/ZmnSCPxj/clboss) plugin on CL, my `backup` grew to 7GB in a few weeks and calling `backup-compact` takes ages, blocks CL and shows no progress bar. The `bacup-cli restore` command is similarly slow (just 10 it/s). This is problematic because you can run out of disk space on the (backup) backend and also restore should not take days.
This PR wants to fix that:
Other ideas:
=> WIP backup: optimize restore and backup-compact

backup/README.md
As instructed here:
https://github.com/ElementsProject/lightning/blob/master/doc/BACKUP.md#backup-plugin-and-remote-nfs-mount
=> added instruction to stop the node before running the plugin

datastore/datastore-plugin.py, datastore/datastore.py, datastore/test_datastore.py
The new datastore PR now has a generation count; this passes
the tests against that now.
Also copies tests from c-lightning, and adds ugprade test.
Changelog-None
=> datastore.py: update to meet new datastore builtin PR.

datastore/test_datastore.py
Reported-by: @cdecker
Closes: #294
=> datastore: don't fail upgrade test if lightningd has real datastore.

autopilot/autopilot.py, autopilot/requirements.txt, autopilot/test_autopilot.py
Initialization for the autopilot plugin would time out due to how long it would take to execute, and lightningd would kill the plugin before finishing. This commit moves the graph calculation routine out of the initialization function to execute after the plugin was initialized. Initialization only reads in options passed from config file or on command line when lightningd was run.
=> autopilot.py: Moved network initialization to new function to fix issues with timeout

rebalance/rebalance.py
I had several successful rebalances, and when I call `rebalancereport` it takes some time to collect info about them.
A possible performance improvement: `rebalancereport` does not call `listpays` for every rebalance one by one, but only once.
In my case, this changes the execution time from ~140 secs to ~7 secs.
=> rebalancereport calls listpays once

summary/summary.py
Knowing the fee per channel is very useful for fee selection.
I assume an option can be added to show the fees only if --details is an argument, but it will make the code a bit less clean.
=> added fee per channel

feeadjuster/feeadjuster.py
feeadjuster crashes when trying to read an non-existing short_channel_id. So better make sure the channel does have one before reading it.
=> skip channels that are not (yet) locked in

feeadjuster/feeadjuster.py
Crashed again for me, this time I assume it is due to me changing the fee strategy to "median" (see stack trace)
Maybe all reads of 'short_channel_id' should be checked?
Also sorry for my incompetence in operating git, to me this shows as 3 commits now m(
```
2022-01-27T16:49:42.133Z INFO    plugin-feeadjuster.py: Plugin feeadjuster initialized (0 base / 250 ppm) with an imbalance of 50%/50%, update_threshold: 5%, update_threshold_abs: 100000000msat, enough_liquidity: 0msat, deactivate_fuzz: None, forward_event_subscription: True, adjustment_method: get_ratio, fee_strategy: get_fees_median, listchannels_by_dst: True
2022-01-27T16:49:42.183Z INFO    [...]-chan#21877: State changed from FUNDING_SPEND_SEEN to ONCHAIN
2022-01-27T16:49:42.907Z INFO    plugin-feeadjuster.py: Adjusted fees of …
```
=> another instance of unchecked short_channel_id access in fee_strategy: get_fees_median

noise/noise.py
Changelog-Fixed: This fixes the problem described in issue #331 . Users are now able to view the latest received message using `recvmsg`
=> Fixes a small bug with noise.py that prevented user from seeing the most recent message id

autopilot/autopilot.py, autopilot/lib_autopilot.py, autopilot/test_autopilot.py
fixes several (not all) testing issues we had with the autopilot plugin.
- fixed a test annotation and CI detection
- fixed a dns.resolver.query deprecation
- added a remark for a possible division by zero (not fixed yet)
- I set the repeated "unable to connect" message to just log-level "warn" so they don't appear as teardown BROKEN errors.
=> fix: autopilot

commando/commando.py
Otherwise it blocks everything while it's working, which can be a
while for a slow command.
Fixes: #347 (I think?)
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
=> commando: make custommsg hook async.

.ci/test.py, .github/workflows/main.yml, autopilot/poetry.lock, autopilot/pyproject.toml, autopilot/requirements.txt, autopilot/test_autopilot.py, backup/poetry.lock, backup/pyproject.toml, backup/requirements-dev.txt, backup/requirements.txt, historian/cli/db.py, historian/poetry.lock, historian/pyproject.toml, historian/requirements.txt, poetry.lock, pyproject.toml
Let's put an end to the eternal dependency issues by specifying exactly what versions we need. May make installing plugins a bit more cumbersome, and we need to migrate quite a few plugins to backfill, but it's purely mechanic,
=> Add support for poetry / PEP 517 based plugins

prometheus/README.md, prometheus/prometheus.py
Make the prometheus plugin listen on 127.0.0.1 (localhost) by default instead of open to the world. This closes a privacy breach in the default configuration.
=> prometheus: Listen on 127.0.0.1 by default

backup/README.md
This simply got missed.
On a fresh install, the command will fail without poetry environment.
=> backup: doc use poetry run also for backup-cli cmd

summary/summary.py
Bitstamp API wants lower case:
https://www.bitstamp.net/api/#ticker
Doesn't work:
https://www.bitstamp.net/api/v2/ticker/BTCUSD/
Works:
https://www.bitstamp.net/api/v2/ticker/btcusd/
=> summary: use lowercase in bitstamp api

.gitmodules, README.md
With the last release of `rust-teos`, I have just discontinued `python-teos`, so it's best to replace the watchtower-plugin link.
=> Replaces python-teos by rust-teos

backup/requirements.txt
This file is referenced in https://lightning.readthedocs.io/BACKUP.html#backup-plugin-and-remote-nfs-mount, but does not exist, making installation and usage of backup plugin much more tricky.
This commit simply adds the two required packages so that the docs are correct now and the plugin can be more easily installed.
=> Add referenced requirements.txt for backup plugin

README.md
This adds a link to the paythrough plugin, which can be used pay an invoice only through a specific channel.
Resolves https://github.com/ElementsProject/lightning/issues/2529
=> Add paythrough plugin link

feeadjuster/README.md, feeadjuster/feeadjuster.py
- We can reduce routing failures by liming the maximum size of outbound HTLCs through a channel
- This change adjusts the max HTLC according to the current liquidity available on a channel.
- I have added this to the feeadjuster plugin to reuse its trigger mechanism and channel balance logic
- The default is for the feature to be turned off so it will not cause unexpected behaviour changes for plugin users who update
- I have also added a basic readme
=> Max htlc option for fee adjuster

feeadjuster/feeadjuster.py
As mentioned in: https://github.com/lightningd/plugins/pull/375#discussion_r956562872 the exclude list needs to be non-required to  run feeadjuster.
Also added the output about the `feeadjuster-exclude.list`file not present or the list of pubkeys.
=> feeadjuster: make exclude list non-required and verbose

README.md
I've been building submarine-swap daemon for boltz.
https://github.com/bitbankinc/NLoop
Since it is now ready to run as a c-lightning plugin, I added a link to README
=> add nloop to README

summary/summary.py
I was getting two `AttributeError`s due to `int`s not being converted to `Millisatoshi`s. Not sure why nobody else was having this issue.
On line 221 - `'int' object has no attribute 'millisatoshis'`
On line 169 - `'int' object has no attribute 'to_btc_str'`
Converting to millisatoshis in two spots fixes the issue.
=> summary: fix attribute errors

rebalance/rebalance.py
It is a performance improvement: `rebalancereport` running time changes from 40 secs to 14 secs on my node.
=> rebalance: listpays use status argument

feeadjuster/feeadjuster.py
- feeadjuster keeps crashing since ages
- this may not be the perfect solution, but fixes the crash
=> feeadjuster: setchannelfee mandatory parameters

drain/README.md
Fix flipped parameter order in documentation so that it matches actual plugin methods https://github.com/lightningd/plugins/blob/master/drain/drain.py#L451
=> drain: README.md fix parameter order

summary/requirements.txt
This should fix the summary with the last version if cln.
Currently summary is crashing on my node, and just install the new version of the pyln-client to get it working again.
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>
=> increase pyln-client version in summary

feeadjuster/README.md, feeadjuster/feeadjuster.py
Currently there is no way to over/underbid the median fees of peers, this PR adds a scaling factor to do so (e.g. set it to `0.5` to calculate fees as if the other peers had 50% lower fees).
=> feeadjuster: Add option to scale median fee adjustment strategy

donations/donations.py, donations/test_donations.py, drain/drain.py, helpme/helpme.py, jitrebalance/jitrebalance.py, jitrebalance/test_jitrebalance.py, monitor/monitor.py, rebalance/rebalance.py, rebalance/test_rebalance.py, summary/summary.py
Recent upstream on cli have seperated `listpeers` and `listpeerchannels` output. This is in deprecation cycle, but CI tests already fail, because they run on `DEPRECATED_APIS=0`.
Affected plugins:
- helpme
- jitrebalance
- monitor
- drain
- rebalance
- summary
- donations (other issues)
=> fix cli upstream changes for `listpeerchannels`

summary/summary.py, summary/test_summary.py
This adds an optional parameter `ascii` to hte `summary` method as well as an plugin option flag `summary-ascii`.
This gives the user the option to use ascii output if requested.
Sometimes useful for fixed fonts and such.
=> summary: request ascii mode

currencyrate/currencyrate.py
```
plugin-currencyrate.py: https://localbitcoins.com/bitcoinaverage/ticker-all-currencies/: USD not in {}
```
=> currencyrate: remove nonfunctional localbitcoins API.

currencyrate/README.md
The actual rate command is `currencyrates` (plural!). I just fixed the README.md, however it would be better to have the plugins name `currencyrate` aligned with its main method to circumvent users having issues trying around with a new plugin.
@rusty: maybe we add a method `currencyrate` (w/o plural) that simply calls `currencyrates`...
=> currencyrate: fix usage type

noise/README.org, noise/noise.py
I have been wanting to add this for a while, but I wanted to wait to see how things would end up with the poetry updates. I'm sorry, I don't know how to write effective tests. All I can really do is reverse engineer existing code and try to hack it into doing something I want. I also updated the readme to change \~last_id\~ to \~msg_id\~ since it was changed like that in the code.
=> Added `allmsgs` command to noise to print all msgs

README.md, archive/commando/README.md
- Remove Archived list from Readme
- Updated archived commando python plugin Readme
=> Removing commando from archived plugins list

rebalance/rebalance.py
- listforwards call takes half a minute on my machine and consumes lots of memory, as I have hundreds of thousands of forwards right now
- it's an option to turn this part of the report off, although by default it's turned on for backward compatibility (others may use this already)
=> rebalance: average forward fee report is optional

README.md
The old badge was pointing to the workflows name
https://github.com/lightningd/plugins/workflows/Integration%20Tests/badge.svg
However this seems to be always failing. Pointing to the workflow file main.yml, which only contains the one integration test workflow, gives a now green badge.
I'm not totally into the github internals, so maybe I'm mistaken on this one. Feedback appreciated.
=> github: fix workflow badge on readme page

.gitmodules, README.md
According to the plugins README this plugin is unmaintained/obsolete. It's also failing it's tests.
=> remove unmaintained nostrify

.github/workflows/main.yml
based on https://github.com/lightningd/plugins/pull/484
Plugins in submodules will get checked out, so they can get tested.
=> Checkout submodules for CI

README.md
* Plugins `autopilot`, `drain`, `rebalance`, and `summary` had been moved to 'archived' but erroneously remained in the available plugins list.
=> Remove plugins autopilot, drain, rebalance, summary from available plugins list

.ci/test.py
I've thought more about https://github.com/lightningd/plugins/pull/487 and since CLN supports basically any language for plugins  i propose to take this generic approach instead.
Non-python plugins put their `requirements.txt` and `setup.sh` in the `tests` folder (the one we already search for executing tests). The bash script will allow python developer to setup the plugin environment as they see fit.
Example [setup.sh](https://github.com/daywalker90/summars/blob/bash-test-setup/tests/setup.sh) from my summars plugin and then a simple switch in my [utils.py](https://github.com/daywalker90/summars/blob/5068ba0a5420be2c9f1147cb824819ea7a89e545/tests/util.py#L15) for local dev and CI
=> Generic plugin support

.gitmodules, README.md
Adds a plugin to hold invoices aka hodlinvoices. For more info see https://github.com/daywalker90/holdinvoice#documentation
=> holdinvoice

.github/workflows/main.yml, .github/workflows/nightly.yml, README.md
* Add a `nightly workflow` to test all (testable) plugins against the CLN `master` branch. 
* Update the `main workflow` to automatically use the `latest` CLN `release` to test against. In the context of a PR only those plugins are tested which had changes or were added to repository. When pushing to master all (testable) plugins will be tested.
=> CI: Add nightly workflow for CLN master; update main workflow to use latest CLN release

sauron/sauron.py
Tested with
```
lightningd --network=signet --log-level=debug --disable-plugin bcli  --plugin ~/plugins/sauron/sauron.py --sauron-api-endpoint https://mutinynet.com/api
```
Should also work for https://mempool.space/signet/api
=> Add support for signet

.ci/test.py
This PR is a temporary fix for the poetry-based backup and donations plugins whose tests are currently failing in CI. Recently released poetry v1.8 seems to cause problems in the current test setup. Pinning poetry to v1.7.1 makes the tests pass again.
=> Pin poetry to 1.7.1 to fix tests for poetry-based plugins

.github/workflows/main.yml
This PR resolves an issue from the latest update to workflow `main`. The workflow currently fails with the error below if it was triggered by a pull request and the head repository's branch is set to `master`.
```
fatal: refusing to fetch into branch 'refs/heads/master' checked out at '/home/runner/work/plugins/plugins'
Error: Process completed with exit code [128](https://github.com/lightningd/plugins/actions/runs/8113474790/job/22176862883#step:8:129). 
```
=> CI: Fix workflow 'main' for pull requests with head repository's branch set to 'master'

.github/workflows/main.yml
This PR intents to fix the logic in CI workflow main.
Previously, we didn't checkout `github.head_ref` for PRs from an external repository before running the test suite.
=> Fix logic in Ci workflow main

.github/workflows/main.yml
This code needs a rewrite so we're deactivating it for now to allow current PRs to be merged without failing CI.
Don't merge until #502, #504, and #505 have been rebased on top and run through CI to make sure there are no further issues with this feature.
=> deactivate pr diff

.gitmodules, README.md
Remove the `python-teos` submodule and replace it by `watchtower` which links to [rust-teos](https://github.com/talaia-labs/rust-teos).
See (https://github.com/talaia-labs/python-teos#state-of-the-project):
> This codebase has been discontinued in favour of its rust counterpart. Please, do check [the new codebase](https://github.com/talaia-labs/rust-teos).
See also: 5f656a1f0f37fa8b431efb248127d221ad9faf8d - Replaces python-teos by rust-teos
=> Remove deprecated python-teos submodule, use rust-teos instead

.gitmodules, README.md
@0xB10C This plugin is archived and has no tests. It should therefore be removed.
=> remove archived c-lightning-plugin-csvexportpays

feeadjuster/README.md, feeadjuster/feeadjuster.py, feeadjuster/test_feeadjuster.py
Ok so i was bored and went over the feeadjuster plugin because @grubles said there were problems with it.
I found a compatibility issue in #457 with `listconfigs` so i made a wrapper function to support both the old and new structure of `listconfigs`.
I went over all the feeadjuster issues that were reporting bugs and most of them are probably users who updated their node but not their `pyln-client`, since we can't raise the version in `requirements.txt` ourselves because that would also break compatibility (maybe fixed by [this](https://github.com/ElementsProject/lightning/pull/7173) ?).
But i also found an actual issue in #199 which i fixed by always getting the channel balance from a rpc call to `listpeers`/`listpeerchannels` instead of doing math with the data from the …
=> feeadjuster: various updates/fixes

.ci/test.py, .ci/update_badges.py, .github/workflows/main.yml, .github/workflows/nightly.yml, README.md
This PR adds two columns for the `main` and `nightly` workflows to the "Available plugins" table in _README.md_ that displays badges indicating plugins' test results:
- **nightly**: Test results from the last scheduled nightly workflow run.
- **main**: Test results from the last workflow run triggered by a push to `master`. Workflow runs triggered by pull requests are ignored.
If a plugin has no tests, no badges are displayed. 
During the above workflow runs various data is generated and saved to the _.badges_ directory of the (to be created) `badges` branch. It is a two step process:
1. At the end of the workflow runs (`build-and-test` and `nightly-build-and-test` jobs) the test result ("passed" or "failed") for each plugin and Python version is saved to a separate file, e.g. …
=> CI: Add two columns for the main and nightly workflows to the "Available plugins" table in README.md

.ci/update_badges.py, .github/workflows/nightly.yml
This PR fixes three issues for the `nightly` workflow related to PR https://github.com/lightningd/plugins/pull/509:
* Missing `python_version` argument for _test.py_.
* Wrong `workflow` argument for _update_badges.py_.
* Wrong path to `gather_data` dir in _update_badges.py_.
=> Bugfix nightly workflow

.github/workflows/main.yml
Right now we are testing all plugins when a PR is created, despite what the comment in main.yml says. This actually implements the functionality described in the comment below `plugin_dirs=`:
```
```
with one addition: we ignore all directories starting with `.` and we ignore paths that are just files without a directory. As a consequence when we only change something in e.g. `.github` everything gets tested and not the `.github` plugin 😄
=> CI: only tests plugins on a PR if they were changed

.github/workflows/main.yml
I moved the check for changed files up and used it to check if on a PR there are files outside the ignored ones changed. Then we onlry run steps if we are pushing or a pr with files changed outside the ignored ones. This gets the "README pr"'s down to <1min, usually ~30s
=> CI: refactor to return success on ignored paths

README.md
We were still pointing to the old external reckless repo 💀 
So i took the opportunity to create an extra plugins manager category and moved reckless there with a link to the cln docs. I also added coffee to the new category.
=> new plugins manager category

.ci/test.py
nightly was having troubles pushing the results to the badges branch. (notice how holdinvoice is still marked failing on nightly, despite all tests passing). This retry logic will fix this.
=> CI: add retry logic for push

.ci/test.py, .ci/utils.py
Currently we are checking the _badges_ branch for testfiles when calling `collect_gather_data`-> `has_testfiles`. That branch is and will not be up2date with the master branch so we should avoid that. And instead of switching branches around i rather save the testfiles once inside the plugin.
=> refactor get_testfiles

.ci/update_badges.py, .github/workflows/main.yml, .github/workflows/nightly.yml
Also invalidates the cache a bit more often: on minor python version updates and whenever ubuntu-latest goes to a new version. 
Also fixes two bugs: 
- we were calling `enumerate_plugins` on the badges branch and not on the master branch
- duplicate `git push` command after the retry loop exits
=> CI: downgrade main python to 3.11, remove unwanted test results

.ci/test.py, .github/workflows/nightly.yml
Right now all plugins fail the nightly python 3.12 tests and are therefore marked as failing for master despite most plugins actually working fine on master.
This is because python dependency management is a mess. The problem was coincurve 18 no longer working in python 3.12.4. We got it updated in CLN but until there is a new python packages release this alone doesn't do anything yet. We should install the dependencies in development mode, which installs them from source. I think this is what we actually want since the purpose is to test the plugins against any changes in CLN and the python framework on master.
You'd think that a simple `poetry install --with=dev` would suffice but you'd be mistaken. Poetry will only install top level dependencies in dev mode and not sub-dependencies. …
=> CI: nightly fixes

currencyrate/README.md, currencyrate/currencyrate.py, currencyrate/requirements.txt, currencyrate/test_currencyrate.py
Currencyrate starts failing tests on master so i took it upon me to look at it and gave i a couple updates.
There was some code for pre v0.9.3, i think we can safely remove that.
The tests failed because of:
```
lightningd-1 2024-07-01T13:02:12.332Z UNUSUAL plugin-currencyrate.py: Traceback (most recent call last):
lightningd-1 2024-07-01T13:02:12.333Z UNUSUAL plugin-currencyrate.py:   File \"/home/runner/work/plugins/plugins/currencyrate/currencyrate.py\", line 156, in <module>
lightningd-1 2024-07-01T13:02:12.333Z UNUSUAL plugin-currencyrate.py:     plugin.options['add-source']['multi'] = True
lightningd-1 2024-07-01T13:02:12.333Z UNUSUAL plugin-currencyrate.py:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
lightningd-1 2024-07-01T13:02:12.333Z UNUSUAL plugin-currencyrate.py: TypeError: …
```
=> Currencyrate update

sauron/sauron.py
Trying to run the sauron plugin today, it appears the Retry constructor may have changed the name of `method_whitelist` to `allowed_methods`.
urllib3 Retry:
https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry
Before changing it I got the error:
(venv) clite@localhost:~$ lightningd --mainnet --disable-plugin bcli --plugin /home/clite/plugins/sauron/sauron.py --sauron-api-endpoint https://blockstream.info/api
2024-07-24T13:54:41.216Z INFO    lightningd: v24.05
2024-07-24T13:54:41.485Z INFO    lightningd: Creating configuration directory /home/clite/.lightning/bitcoin
2024-07-24T13:54:41.487Z INFO    plugin-manager: /home/clite/lightning/usr/libexec/c-lightning/plugins/bcli: disabled via disable-plugin
2024-07-24T13:54:41.944Z INFO    plugin-wss-proxy: …
=> sauron: changed Retry param name from method_whitelist to allowed_methods

archived/prometheus/prometheus.py
Fixes Prometheus metrics conversion from msat to sat:
```
...
2024-08-12T11:14:18.220Z UNUSUAL plugin-prometheus.py:     [o['amount_msat'].to_satoshi() for o in funds['outputs']]
2024-08-12T11:14:18.220Z UNUSUAL plugin-prometheus.py: AttributeError: 'int' object has no attribute 'to_satoshi'
...
```
=> Prometheus: Fix msat to sat conversion

.gitmodules
This was causing reckless to fail when users don't have a github credential with ssh access. See
https://github.com/ElementsProject/lightning/issues/7635
=> remove ssh requirement for torq plugin

rebalance/rebalance.py
I think it is nice to know what was the fee percentage that was used in the re-balance, 
e.g. 
Instead of this:
fee": "59846msat",
It will output:
fee": "59846msat (0.114%)",
=> add fee percent that was taken in a successful rebalance

README.md
Add a contributions section to the README.md and add commits format. Related to: #49.
=> Update README.md with contributions format

.ci/test.py
We don't upgrade python dependencies in the other types (python/poetry). This would cause the generic type to upgrade `pyln-testing` beyond the tested CLN version and `pyln-testing` is not always backwards compatible.
Example run with fix: https://github.com/daywalker90/plugins/actions/runs/12252218795
Issue reported by @chrisguida on discord
=> CI: don't upgrade generic env's python dependencies

.github/workflows/nightly.yml
Also lets not assume the amount of cores the CI has. For some reason during make install cargo is being run which is not available in the default sudo env. This change makes it available.
Fixes #621
=> CI: setup cargo env for nightly make install

datastore/test_datastore.py
By default listdatastore in cln 24.11 contains an "askrene" object. So i changed these lines to only check for inclusion and not equalness.
=> datastore tests: handle cln v24.11+ default non-empty listdatastore

.ci/test.py
We can't let plugins dictate which version of pyln-testing will be installed for testing. Due to missing backward/forward compatibility and no way for plugin repos to tell which CLN versions they are being tested on we must set the correct pyln-testing version. For this i added/moved this to the last step of setting up the pyton environments.
=> CI: we decide the pyln-testing version to be installed

.ci/test.py
In the generic setup the python dependencies installation should be done before custom code from the setup.sh is executed. Since `install_dev_pyln_testing` installs things like `protobuf` the version can change between generating grpc bindings and running the tests which causes errors (see holdinvoice erroring on nightly but not 24.11)
=> CI: install pyln-testing before running generic setup

.ci/test.py, .github/workflows/main.yml, .github/workflows/nightly.yml
I saw some fresh problems in the CI with poetry in python 3.11:
```
The command "export" does not exist.
```
```
Warning: The current project could not be installed: No file/folder found for package cln-meta-project
If you do not want to install the current project use --no-root.
```
I remembered this deprecation warning:
```
Warning: poetry-plugin-export will not be installed by default in a future version of Poetry.
In order to avoid a breaking change and make your automation forward-compatible, please install poetry-plugin-export explicitly. See https://python-poetry.org/docs/plugins/#using-plugins for details on how to install a plugin.
```
So i added the dependency manually aswell as the --no-root. Let's hope it doesn't break the other versions.
=> Poetry deprecation fixes

donations/poetry.lock, donations/pyproject.toml
The recent PR to install pyln-testing after a plugin's dependencies causes issue for this plugin because some dependencies were incompatible with the cln dev env we install with pyln-testing. The easiest fix for me is to just update the dependencies of donations. They were updated in a way that they are still compatible with the python versions we test.
=> donations: upgrade dependencies

sauron/requirements.txt, sauron/tests/test_sauron_esplora_bitcoin.py, sauron/tests/test_sauron_esplora_signet.py, sauron/tests/test_sauron_esplora_testnet.py, sauron/tests/test_sauron_esplora_tor_proxy.py, sauron/tests/test_sauron_mempoolspace_signet.py, sauron/tests/util.py
cln-grpc was dying and taking the rest of lightningd with it (because it's important) because it was trying to listen on port 9736 in multiple tests simlutaneously. this PR allows the sauron tests to take advantage of the new plyn-testing feature that assigns the grpc plugin a random unused port by default. sauron's tests were previously overriding these values in its override fixtures, and this PR corrects that. there is still some brittle- ness around the `TEST_NETWORK` global variable, but setting it in the override `LightningNode` fixture at the top of each test, immediately before the call to init the superclass, appears to make the tests pass, so we'll leave it like this for now.
we also remove the pin to `pyln-client` 24.05, as this requirement no longer seems necessary.
this fixes …
=> sauron: make tests more robust

.github/workflows/main.yml, prometheus/README.md, prometheus/prometheus.py
This introduces `uv`, which allows for simpler and more automatic dependency management. Solely having `uv` installed in the environment allows the plugin to work as expected, while its deps are installed at runtime.
The `shebang` at the top of the `prometheus.py` strictly enforces `uv`, so I've left a note in the README on how to revert to `poetry`.
=> prometheus: Add uv support with inline deps

.ci/test.py, .ci/utils.py, .github/workflows/main.yml
- Support uv projects, refactored the explicit tmp directory creation to not run for uv projects
- Update python 3.12 to 3.13 in the matrix (torq-plugin needs to update dependencies for 3.13)
- Detect poetry and uv projects by their .lock files to differentiate them (if both are present due to migration prioritize uv)
- Don't check out lightning repo and pull the published pyln-* packages instead with the matching version to CLN
- Save cache more often, they get deleted after a week anyways and it speeds up PR runs
=> CI: update main and add uv support
