lightningd/plugins

- rebalance/README.md
- rebalance/rebalance.py
- this plugin helps to move some liquidity between your channels using circular payments
- previous conversations here: ElementsProject/lightning#2567
> rebalance plugin in python

- .gitmodules
> created git module for c-lightning-api plugin

- README.md
- sendinvoiceless/README.md
- sendinvoiceless/sendinvoiceless.py
- sends payment without an invoice from the receiving node
- uses circular payments: takes the money to the target node, pays in the form of routing fee, and brings some change back
- no plugin/update required on the receiving side
> invoiceless payment plugin

- README.md
added another community repo, a tutorial video for pypi lightning and in particular added instructions how to run and activate plugins.
> enhanced the README.md file

- rebalance/rebalance.py
> rebalance: exclude all own channels from getroute

- probe/probe.py
It was returning `null` and we'd have to check the logs or the DB for the
result. This makes it just a bit easier to see what happens.
> probe: Actually add a sensible return value to the probe method

- .gitmodules
Added a new jwt-factory submodule and pointed graphql submodule to latest commit
> updated graphql submodule. Added new jwt-factory submodule

- summary/summary.py
This cool PR will add a descriptive table header to the summary output like this:
Note: The markdown doesn't render the correct fixed width on boxlines. 
```
├990µbtc      OUT/OURS ┼ IN/THEIRS     990µbtc┤ SCID           FLAG ALIAS
├──────────────────────╢                        1515136x109x0  [__] CoinGate
├────────────────────┼─┤                      1511205x23x0   [__] lnd.fun
╟──────────────────────┤ 1514942x51x0   [__] dead.cash
├─────────────────────┼┤                       1514970x12x0   [__] aranguren.org
├──────────────────────╢                        1515133x10x0   [__] 1ML.com node ALPHA
├──────────────────────╢                        1515135x50x0   [__] lightning.glop.org
```
> feat: summary adds descriptive table header

- README.md
At https://github.com/fiatjaf/lightningd-gjson-rpc/tree/master/cmd.
Including `waitpay` and `webhook` plugins for now.
> add my own plugin collection

- rebalance/README.md
- rebalance/rebalance.py
- sendinvoiceless/README.md
- sendinvoiceless/sendinvoiceless.py
- summary/README.md
- summary/summary.py
This is a **work in progress** PR on refinements I discovered when implementing the `drain` plugin (#22)
Affects `rebalance`, `sendinvoiceless` and `summary`.
> Cleanup rebalance sendinvoiceless

- helpme/Makefile
- helpme/README.md
- helpme/helpme.py
- summary/summary.py
This plugin autoconnects to a few nodes, and offers some useful advice.  It's an eternal Work In Progress, but the idea is that it will expand to become all-encompassing and Know Everything!
> helpme: new plugin.

- README.md
- monitor/README.md
- monitor/monitor.py
- monitor/requirements.txt
It seems I completely butchered the previous PR into becoming unmergeable. So this is just an attempt to get it working again.
> Rene's monitor plugin

- monitor/requirements.txt
- persistent-channels/requirements.txt
- probe/requirements.txt
And remove blank lines from monitor's and persistant-channels' requirements.
> Add a 'requirements.txt' to probe plugin

- probe/probe.py
We also make the probes asynchronous allowing for multiple probes to be in flight concurrently.
> probe: Add some enhancements (probe specific node and traceroute)

- monitor/monitor.py
Make monitor use the `"format-hint": "simple"`. And some quick drive-by cleanups.
> monitor: human readable output

- rebalance/rebalance.py
This is less readable, but compatible with Python3.5
> rebalance: restore Python3.5 compat

- drain/drain.py
... sorry, i just sit down and made the cleanup commit a little too late.
This fixes:
- division by zero when gossip was not up to date yet.
- uninitialized variable payload on read_params when asserting too early.
> drain: cleanups

- donations/requirements.txt
It made all other PRs buidl to crash
> donations: bump flask-wtf requirement / repair Travis

- sauron/sauron.py
Fixes #94.
This gets rids of bc.info to use the Esplora raw blocks API, and add some cleanups
> Sauron improvements

- autopilot/c-lightning-autopilot.py
- sauron/sauron.py
- summary/summary.py
Looks like I missed some `lightning` imports last time... Remarked when testing https://github.com/ElementsProject/lightning/pull/3679
> Misc cleanups

- prometheus/prometheus.py
This PR adds a bunch of forwarding metrics that allow to analyze which channels are useful and which could be closed.
> Prometheus: Add forwarding and fee metrics

- README.md
- drain/README.md
- drain/drain.py
- drain/test_drain.py
- drain/utils.py
@cdecker  This PR is (currently) for me if ln plugins and travis is working for me. Ignore it until I finished my code...
> test drain plugin

- jitrebalance/jitrebalance.py
- jitrebalance/test_jitrebalance.py
- jitrebalance/tests/hold_htlcs.py
- jitrebalance/tests/refuse_htlcs.py
Just need to add tests now (and potentially the second point of https://github.com/lightningd/plugins/issues/120#issue-625570619)
Based on https://github.com/lightningd/plugins/pull/115
> Misc Jit-rebalance plugin enhancements

- sauron/requirements.txt
Fixes https://github.com/lightningd/plugins/issues/126
> sauron: fix pip requirements..

- .gitmodules
- README.md
Because I wasn't working well with a big plugin monorepo.
> add trustedcoin, sparko and webhook to the main list.

- README.md
> readme: Added two new plugins by @rbndg

- helpme/helpme.py
Reported-by: Sebastian Falbesoner <@theStack>
Fixes #107
> helpme: Verify that the caller has specified an invoice

- sauron/sauron.py
Cf the discussion on IRC. My guess is that Esplora's estimation depends on the buckets to be filled and that there are not enough transactions on testnet, so better to special-case it.
> sauron: handle testnet API unreliability

- jitrebalance/jitrebalance.py
This fixes the crashes i've been experiencing for a while :tada:
> jitrebalance: channel lookup can fail

- autopilot/autopilot.py
Avoiding zero division error and improve calculation of available funds.
> Fixing bugs in autopilot

- backup/README.md
- backup/backup.py
- adds a basic quick to read/use README.md for this plugin.
- fixed a loglevel DEBUG issue
> backup: add README.md

- feeadjuster/feeadjuster.py
- feeadjuster/test_feeadjuster.py
Some nits i [had left](https://github.com/lightningd/plugins/pull/160#pullrequestreview-540131405) but didn't want to make gallizoltan rework it once again
> feeadjuster: Feeadjust method followup

- drain/drain.py
- drain/requirements.txt
- drain/test_drain.py
- drain/utils.py
There were incompatibilities introduced by main repository changes...
> drain: fix test and millisatoshi from float

- README.md
This is the tiniest of PRs, but I think it helps to provide an example test that actually passes.
> Fix example test

- prometheus/prometheus.py
Correct comment indentation and don't mix up scid with alias as per https://github.com/lightningd/plugins/pull/152#discussion_r512623918
> prometheus: small fixups

- helpme/helpme.py
- helpme/test_helpme.py
This plugin was having certain incompatibilities with more recent c-lightning versions.
- check for config files for network and global
- check when all funds were used for channels
- check for installed plugins via `rpc.listconfigs`
> Cleanup: helpme plugin

- backup/backup.py
Fix #183. At least I think this was the intent.
> backup: Increase version_count after each version

- backup/README.md
I was confused by a few things in the backup README so I clarified them, feel free to comment if I still got anything wrong 😄 . Also a few minor style fix-ups.
> backup: Some improvements to text of README.md

- feeadjuster/feeadjuster.py
- feeadjuster/test_feeadjuster.py
> feeadjuster: option to handle big channels differently

- README.md
- request-invoice/README.md
- request-invoice/requestinvoice.py
- request-invoice/requirements.txt
- request-invoice/test_request-invoice.py
I couldn't rebase the origin PR #90 because it was created off of @alex-Codelab's `master`,
> Request invoice plugin

- backup/README.md
I tried a few times to init it with a directory, now I saw a guy on IRC stumbling across the same issue....
> clarify backup location to be a file

- .gitmodules
- README.md
Adds a watchtower client plugin to connect to The Eye of Satoshi instances via HTTP(s).
> Adds watchtower client to plugins

- feeadjuster/feeadjuster.py
possibility to turn off the forward event with config or plugin method
> feeadjuster: forward event switch

- README.md
- currencyrate/Makefile
- currencyrate/README.md
- currencyrate/currencyrate.py
- currencyrate/requirements.txt
I'm enabling offers in alternate currencies using this API, so here's an implementation.
> currencyrate: new plugin.

- rebalance/rebalance.py
- turns off feeadjuster's automatic fee updates while rebalance running
- runs feeadjust only once, at the end
- measures time for rebalance
> rebalance: better feeadjuster integration

- rebalance/rebalance.py
- rebalance/test_rebalance.py
As @aido found commented in #205 we had a division by zero issue in rebalance: https://github.com/lightningd/plugins/issues/205#issuecomment-770545323
> rix: rebalance divsion by zero

- rebalance/rebalance.py
log messages show how much time need for an HTLC settlement
> rebalance: measure and log HTLC settlement time

- summary/README.md
- summary/summary.py
Hi,
It might be nice to see `fees_collected_msat` in summary output
> summary: Add fees_collected info to output

- rebalance/rebalance.py
A channel can exist without a short_channel_id, in the CHANNELD_AWAITING_LOCKIN state, while the funding transaction is sent but not yet included in a block.
Running `rebalanceall` while opening a channel could throw an exception:
```
2021-02-14T09:31:39 UNUSUAL plugin-rebalance.py: Exception in thread Thread-5:
2021-02-14T09:31:39 UNUSUAL plugin-rebalance.py: Traceback (most recent call last):
2021-02-14T09:31:39 UNUSUAL plugin-rebalance.py:   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner
2021-02-14T09:31:39 UNUSUAL plugin-rebalance.py:     self.run()
2021-02-14T09:31:39 UNUSUAL plugin-rebalance.py:   File \"/usr/lib/python3.6/threading.py\", line 864, in run
2021-02-14T09:31:39 UNUSUAL plugin-rebalance.py:     self._target(*self._args, **self._kwargs) …
```
> rebalance: channel wo scid

- rebalance/rebalance.py
In rare cases, HTLCs can be stuck for days. I don't know why it's happening, maybe it would worth investigating the situation.
My `listpeers` look like this:
```
$ lightning-cli listpeers
<...>
"htlcs": [
{
"direction": "out",
"id": 6317,
"msatoshi": 624610838,
"amount_msat": "624610838msat",
"expiry": 670920,
"payment_hash": "fbc58fcada2d3652c4bfb8f7474f0671b45024dec1f0aee2eb813295cd7c2f0c",
"state": "SENT_ADD_ACK_REVOCATION"
}
]
<...>
"htlcs": [
{
"direction": "out",
"id": 58395,
"msatoshi": 121953259,
"amount_msat": "121953259msat",
"expiry": 669832,
"payment_hash": "f19587efc60bae52e87b46ff8fe7eb019ca82f99cc0fbe94bcaa428c759d045d",
"state": "SENT_REMOVE_ACK_COMMIT"
}
]
<...>
```
> rebalance: handle HTLC timeout

- rebalance/README.md
- rebalance/rebalance.py
- `rebalancereport`: shows information about rebalance
- some README update
> rebalance report

- rebalance/rebalance.py
`rebalancereport` shows a score that reflects liquidity health
* its value between 0% and 100% depending on liquidity distribution
* running `rebalanceall` may increase the score, and surely not decrease (if no forward event occurs meanwhile)
> rebalance: measure liquidity health

- summary/summary.py
- summary/summary_avail.py
- summary/test_summary.py
Just improves on tests by adding some useful logging
> summary: maintenance

- summary/test_summary.py
This will make the test to wait
for one node to see that a second node
disconnected after using .stop().
For that it adds wait_for(lambda) testing utils method.
> summary: fix another flake

- drain/drain.py
> drain: fix a broken log statement expansion

- backup/socketbackend.py
Add automatic reconnect (with exponential back-off) to the socket backend.
If the connection is lost while pusing a change, try to reconnect. Handle edge-cases that might come up depending on when the disconnect happaned.
Currently the parameters are hardcoded: it will retry 5 times, on the first retry it will wait 5 seconds before reconnecting. There is an exponential backoff of 1.5, so on the fifth try it will wait about 25 seconds.
This is particularly useful when conencting over Tor, as transient interruptions are fairly common there.
Example output (reconnecting after one try):
```
2021-03-01T07:48:45.673Z INFO    plugin-backup.py: Connection was lost while sending change (retry 1 of 5, will try again after 5 seconds)
2021-03-01T07:48:50.802Z INFO    plugin-backup.py: Connecting to …
```
> backup: Implement automatic reconnect in socket backend

- jitrebalance/test_jitrebalance.py
> jitrebalance: fix missing payment_secret for sendpay

- rebalance/rebalance.py
Using dynamic feeadjuster this can help us better understand our current usage
> rebalance: add average_forward_fee_ppm for 1s 7d and 30d interval to rebalancereport

- feeadjuster/feeadjuster.py
This disables scaling of the base fee based on channel distortion and
instead always sets global config base fee.
The rationale behind this is that the base fee is meant to cover the
'fixed risk' of accepting an HTLC. In reality the risk may vary,
but this is unrelated on channel balance distortion but other factors.
We can have dynamic base fee per channel if we implent a better way
of competing and cost/risk coverage for this value.
> feeadjuster: disable dynamic base fee scaling

- rebalance/rebalance.py
this occurs if I don't have any transaction forward for a day
> rebalance: division by zero fix

- feeadjuster/feeadjuster.py
This adds an optional paramter to the `feeadjust` method which is `scid`
that will, if set, only adjust one channel. Default remains None which
will adjust all channels.
> feeadjuster: feature to adjust a specific channel

- paytest/paytest.py
Reported-by: Rene Pickhardt <@renepickhardt>
> paytest: Fix an error when we unexpectedly get a LegacyPayload

- .ci/test.py
- .github/workflows/main.yml
- .gitignore
- autopilot/test_autopilot.py
c-lightning changed a bit under our feet. This catches up with it.
> Fix Github Actions

- historian/historian.py
This check was introduced to protect against the length being
corrupted but we now get some node_announcements with huge
feature-bits, triggering this rule. Let's skip them instead.
> historian: Instead of exiting just skip large messages

- .gitmodules
- README.md
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>
> Adding go-lnmetrics.reporter

- donations/README.md
@renepickhardt The default port seems to be 8088 and there were some misleading lines in the README file.
> donations/README.md: Default port is 8088

- rebalance/rebalance.py
This PR removes opaque and unintuitive "Sending <amt+fees>msat over <n> hops to rebalance <amt>msat" debug messages and replaces them with non-debug "<n> hops and <fees>sat fees for <amt>sat along route: our alias -> outgoing peer alias -> some node alias -> ... -> incoming peer alias -> our alias".
Salient changes:
- Breaks down fees and rebalance amount separately
- Uses satoshi units instead of harder-to-read msatoshi units
- Shows the attempted route in a human-readable format
- Promotes route attempt messages from 'debug'
> rebalance: Print human-readable route details with satoshi units and node aliases

- summary/summary.py
This commit try to solve the following exception with an additional sanity check:
```
{
"code": -32600,
"message": "Error while processing summary: 'Plugin' object has no attribute 'persist'",
"traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/pyln/client/plugin.py\", line 627, in _dispatch_request\n    result = self._exec_func(method.func, request)\n  File \"/usr/local/lib/python3.8/site-packages/pyln/client/plugin.py\", line 609, in _exec_func\n    return func(*ba.args, **ba.kwargs)\n  File \"/home/_lightning/plugins/summary.py\", line 124, in summary\n    addpeer(plugin, p)\n  File \"/var/git/plugins/summary/summary_avail.py\", line 7, in addpeer\n    if pid not in p.persist['peerstate']:\nAttributeError: 'Plugin' object has no attribute …
```
> Make a sanity check during the initialization of the db

- README.md
- drain/drain.py
- feeadjuster/feeadjuster.py
- summary/summary.py
Just some general code cleanups and a readme thing
> cleanups: feeadjuster, drain and summary

- noise/noise.py
- noise/test_chat.py
This addresses issues raised by #332
- reverts #332
- fixes #331
- adds testcase for issue described in #331
- adds missing docstrings
- cleanup some nits
> fix: noise

- drain/test_drain.py
- feeadjuster/feeadjuster.py
this will make plugins compatible to the upcoming new `setchannel` command
> upgrade: new setchannel command

- commando/README.md
- commando/commando.py
- commando/test_commando.py
> Larger commando commands

- feeadjuster/feeadjuster.py
Addresses proposed improvement: https://github.com/lightningd/plugins/commit/5c43c7f3bf75862d80a00a35163ad8d6af9f7fa7#r72287918
> feeadjuster: improve setchannelfee deprecation detection

- README.md
This adds c-lightning.ts. It is designed to be mostly compatible with clightningjs, but introduces some new features and works better with TypeScript.
> Add TypeScript API

- rebalance/requirements.txt
A simple update to resolve issue #312
> Update required pyln-client version

- backup/README.md
> now uses poetry to manage dependencies

- feeadjuster/feeadjuster.py
skip setting channels with the IDs in the `feeadjuster-exclude.list` file
Fixes: #165
The simplest solution I could come up with to achieve not setting all channels when running:
`lightning-cli feeadjust`
To not create a new file a config option would need to be created for each pubkey something like:
```
"options": [
{
"name": "exclude",
"type": "string",
"default": 0,
"description": "A pubkey of a node to not adjust the channels with.",
"multi": true
}
```
then would need to parse the multiple entries into a list.
I think it is more useful to have a separate list so the list of pubkeys don't need to be deleted if one stops using the feeadjuster temporarily.
> add option to exclude channels with nodes

- commando/commando.py
> commando: change underscore to dash

- helpme/helpme.py
> Fixes helpme.py improper calculation of num invoices paid and available out of channel funds

- .gitmodules
- README.md
`circular` is a plugin that helps routing nodes rebalance their channels. It features a custom pathfinding algorithm that gathers liquidity information from failed payments and uses it to be as effective as possible.
> Add `circular` to the list of plugins

- .gitmodules
- README.md
plugin: update references to submodule : `python-teos`
> plugin: update references to submodule python-teos

- rebalance/rebalance.py
waitsendpay could stuck for minutes making rebalancestop unresponsive
> rebalance: rebalanceall can be stopped quickly

- rebalance/rebalance.py
- rebalance/test_rebalance.py
`rebalanceall` can run on multiple threads for faster results
> rebalance: multithreading

- backup/backend.py
- backup/backends.py
- backup/backup.py
- backup/filebackend.py
- backup/protocol.py
- backup/server.py
- backup/socketbackend.py
- backup/test_backup.py
Just code nits and minor changes, but since its an important plugin, we make a proper PR :)
> cleanup: backup

- .ci/test.py
- .github/workflows/main.yml
We have a couple of workflow config issues running CI since a long time.
Lets try to address them.
> github: fix CI workflows

- .github/workflows/main.yml
- autopilot/test_autopilot.py
- backup/test_backup.py
- noise/noise.py
This removes debug output and corrects some code nits that have been introduced by the big CI restoration PR #418
> chore: some cleanups and minor fixes

- README.md
> nostrify: Broken Link in README

- summary/summary.py
- summary/summary_avail.py
- summary/test_summary.py
- Adds sort config option and adds custom argument, e.g.  `lightning-cli summary sortkey=total`
- Replaces the usage of shelve by hex dumps of pickle serialized objects.
> summary: improvements

- .github/workflows/main.yml
> Update Actions to v3 to fix Node.js 12 Warnings

- README.md
- clearnet/README.md
- clearnet/clearnet.py
- clearnet/requirements.txt
- clearnet/test_clearnet.py
This plugin can be used to optimize usage of clearnet connection over TOR (when possible).
> clearnet: adds clearnet plugin

- donations/poetry.lock
- donations/pyproject.toml
Reverts lightningd/plugins#521
> Revert "build(deps): bump werkzeug from 2.3.8 to 3.0.3 in /donations"

- .ci/test.py
- .ci/update_badges.py
- .ci/utils.py
- .github/workflows/main.yml
- .github/workflows/nightly.yml
* Refactor Python code:
* Move duplicate code from _test.py_ and _update_badges.py_ into new file _utils.py_
* Add some type annotations
* Fix `setup-python` action in workflow files
* Cleanup
> Refactor CI

- backup/README.md
> fix backup.md broken link

- .gitmodules
- README.md
@fiatjaf  This plugin is archived and has no tests. It should therefore be removed.
> archive plugin sparko

- .github/workflows/main.yml
Lets not run tests on these files/directories. There is no point
> CI: ignore some paths from tests

- .gitmodules
- README.md
Plugin to allow/deny incoming channel opens based on lists and/or a custom rule: https://github.com/daywalker90/clnrod
> adding clnrod

- README.md
- archived.md
Moved the Archived Plugins section to a new archived.md file
> Moved the Archived Plugins section to a new archived.md file

- .github/workflows/main.yml
- .github/workflows/nightly.yml
Let's test for the latest bitcoind, just like we do in lightningd
> update bitcoind to 27.1

- currencyrate/currencyrate.py
> removing bitstamp from sources and fixing the request for coinbase api

- .github/workflows/main.yml
https://www.upwind.io/feed/github-actions-supply-chain-compromise-tj-actions-changed-files-action
> CI: remove compromised changed-files action

- .github/workflows/main.yml
This reverts commit d4287139e7c667bbf467097a9bbc8b56684082e2.
Author claims to have removed the problematic commit and implemented measures to prevent it in the future. https://github.com/tj-actions/changed-files
> Revert and update "CI: remove changed-files action"
